// All chain ids come from Vite env (generated by scripts/gen-env.mjs).
// Never hardcode object ids in source (spec §2).
const env = import.meta.env;

function req(name: string): string {
  const v = env[name];
  if (!v) throw new Error(`${name} missing — run \`pnpm gen-env\` first`);
  return v as string;
}

export const PKG = req("VITE_PKG");
export const RPC_URL = req("VITE_RPC_URL");
export const REGISTRY_ID = req("VITE_REGISTRY_ID");
export const CLOCK_ID = "0x6";

// Derive network from the RPC endpoint so the explorer links match the chain
// we're actually reading (mainnet/testnet/devnet), defaulting to testnet.
export const NETWORK: "mainnet" | "testnet" | "devnet" =
  /mainnet/.test(RPC_URL) ? "mainnet" : /devnet/.test(RPC_URL) ? "devnet" : "testnet";

/** Block-explorer URL for a transaction digest (Suiscan). */
export const explorerTxUrl = (digest: string): string =>
  `https://suiscan.xyz/${NETWORK}/tx/${digest}`;

export interface MarketConfig {
  label: string;
  marketType: string; // phantom M
  policyId: string;
  oracleId: string;
}

export const MARKETS: MarketConfig[] = [
  {
    label: "SUI/USD",
    marketType: "0x2::sui::SUI",
    policyId: req("VITE_POLICY_ID"),
    oracleId: req("VITE_ORACLE_ID"),
  },
];

export const MAX_BPS = 10_000;
export const TIMELOCK_MS = 259_200_000; // 72h, mirrors upgrade_registry::TIMELOCK_MS
